apiVersion: v1
kind: ConfigMap
metadata:
  name: aarogyaNet-config
  namespace: aarogyaNet
data:
  DB_URL: jdbc:postgresql://postgres:5432/aarogyaNet
  DB_USERNAME: aarogyaNet_user
  SERVER_PORT: "8080"
  CORS_ORIGINS: http://localhost:3000